name: nightly_test

on:
  workflow_dispatch:
  schedule:    
    - cron: "0 0 * * *"
    
jobs:

  nightly_test:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          lscpu
